@startuml réalisation de cas d'utilisation du redemmarage du jeu
title RDCU pour redémarrerJeu
skinparam Style strictuml

participant ":JeuDeDes" as c
participant "joueurs: Map<String,Joueur>" as jm

-> c : redémarrerJeu()
note right: Selon Contrôleur\n(JeuDesDés est \nl'objet racine)
c -> jm : clear()
note right: Selon Expert
@enduml